version: '2'

volumes:
  egdb:
      driver: 'local'
services:
  db: 
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - egdb:/var/lib/postgresql/data/pgdata
  web:
    image: 666552473144.dkr.ecr.ap-northeast-1.amazonaws.com/engenius/repo:latest
    ports:
      - "3000:3000"
    links:
      - db:postgres
    environment:
      - ENGENIUS_DATABASE_USERNAME=engenius
      - ENGENIUS_DATABASE_PASSWORD=engenius
    container_name: engenius
    stdin_open: true
    tty: true
